# Generated by Django 4.2.13 on 2024-05-23 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("age", models.IntegerField(default=20)),
                ("phone", models.CharField(max_length=16)),
                ("addtime", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "myapp_user",
            },
        ),
    ]
